apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  annotations:
    demoless/app: "app1"
  labels:
    app: app1
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        demoless/app: "app1"
      labels:
        app: app1
    spec:
      containers:
        - name: nginx
          image: "nginx:1.19"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: 1Gi
              cpu: "1"
            limits:
              memory: 1Gi
              cpu: "1"
          livenessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: 80
          startupProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: 80
          lifecycle:
            postStart:
              exec:
                command:
                  - hostname > /usr/share/nginx/html/index.html
