name: Docker Image CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag demoless
      - name: Run Docker
        run: |
          docker run --rm  demoless --help
